### ISSUE TITLE
Some repo tags give 500 error messages

### ISSUE THREAD

**Issue by brunnels** [parabuzzle/craneoperator#16]
I pushed some jhipster images to my private registry and when I click their tags I'm seeing just the red spinner and when I investigate in chrome dev tools I see:
```
ArgumentError at /container/jhipster/jhipster-registry/tags.json
Malformed version number string v2.5.0
file: version.rb location: initialize line: 206
```
Also occurring with jhipster-console, jhipster-elasticsearch, and others.

I'm using parabuzzle/craneoperator:2.1.0

**Comment by parabuzzle** [comment]
Hmm.. that's no good. I'll look in to it. What version of the registry are you using?

**Comment by brunnels** [comment]
Using registry:2.  I can change to registry:latest if you think that would be better.

**Comment by parabuzzle** [comment]
@brunnels I found the issue in the version sorting code. It didn't like letters in valid version numbers very much. version 2.1.1 of the container should have the fix in it :)

**Comment by brunnels** [comment]
That resolved the issue with the broken tags but broke the ones that were working. :smile: 

0.0.4-SNAPSHOT

```
ArgumentError at /container/network-automation/uaa/tags.json
Malformed version number string 0.0.4-
file: version.rb location: initialize line: 206
```

**Comment by parabuzzle** [comment]
damnit!

**Comment by parabuzzle** [comment]
@brunnels ok.. so that was a dumb oversight on my part.. should be good now in version 2.1.2

**Comment by brunnels** [comment]
Awesome,  Thank you.  Just verified everything is working now.  Thanks again for your quick support and updates.  Wish I could vote you up on docker hub or something.
