### ISSUE TITLE
Uncaught Error: Cannot find module "prop-types"

### ISSUE THREAD

**Issue by sendit2me** [parabuzzle/craneoperator#24]
I keep getting 

Uncaught Error: Cannot find module "prop-types"

when starting the container, and attaching to a local registry, have tried a number of settings.

**Comment by parabuzzle** [comment]
hmm.. that may be a build problem. I'll take a look later today. 

What version of the container are you using?

**Comment by xavierdavidgarcia** [comment]
Any news on that ? I have the same error. Thank you

**Comment by parabuzzle** [comment]
I'm not able to reproduce it locally... 

What version of the container are you using?
What browser and browser version are you using?

**Comment by haphan** [comment]
Happens to me as well, i will post more details how to reproduce the issue later.

![](http://i.imgur.com/yr5NUwO.png)

**Comment by haphan** [comment]
Okay, I believe something wrong with the docker image published in store.docker.com

It works when I rebuild the docker image locally. I am putting steps here in case anyone need it.  @xavierdavidgarcia 

```bash
$ git clone https://github.com/parabuzzle/craneoperator.git && cd craneoperator

$ gem install httparty memoist

$ npm install && npm install webpack

$ rake build

$ docker build -t registry-ui:latest .

docker run -d \
  -p 8123:80 \
  -e REGISTRY_HOST=registry.example.com \
  -e REGISTRY_PORT=443 \
  -e REGISTRY_PROTO=https \
  -e REGISTRY_SSL_VERIFY=true \
  -e REGISTRY_USERNAME=xxxx \
  -e REGISTRY_PASSWORD=xxxx \
  -e USERNAME=admin \
  -e PASSWORD=xxxxx \
   registry-ui:latest

```

**Comment by elsmorian** [comment]
I am also getting this on the latest version, though version 2.1.3 works ok :)

**Comment by parabuzzle** [comment]
can you check version 2.1.5 please?

**Comment by leominov** [comment]
`2.1.5` works fine for me.

**Comment by TheBay0r** [comment]
had the prop-types issue yesterday with `2.1.4` as well. `2.1.5` seem to resolve that issue 👍

**Comment by parabuzzle** [comment]
Problem was in the webpack build.
