### ISSUE TITLE
Switch from 80 to 8080 port

### ISSUE THREAD

**Issue by leominov** [parabuzzle/craneoperator#26]
Application must have unusual rights (CAP_NET_BIND_SERVICE) to running on 80 port, best choose is switch to free-to-binging port.

**Comment by parabuzzle** [comment]
the port this is listening on is inside the container. You can map to whatever you want on your host (ie: `-p 8080:80`. You don't need any special privileges for that. 

If you're using `--net=host` then yes you will need more privileges but if you're using `--net=host` then you should have the privileges to do it.

**Comment by leominov** [comment]
My comment about privileges in container. By default you running application by root and with some default rights. But if you running it by non-root user and drop all capabilities, you must set `CAP_NET_BIND_SERVICE ` to allow binding 80 port. This may happen, for example, in Kubernetes cluster with security context restriction.

**Comment by parabuzzle** [comment]
Would it make sense to just make the port configurable with an ENV variable? say, `-e PORT=8080`

**Comment by parabuzzle** [comment]
@leominov looks like it already supports injecting custom port.. just use `-e PORT=8080`

**Comment by leominov** [comment]
Nice, thanks @parabuzzle for your attention
