### ISSUE TITLE
Pagination for repositories listing

### ISSUE THREAD

**Issue by leominov** [parabuzzle/craneoperator#27]
Hello

By default `/v2/_catalog` return only 100 repositories.

* https://docs.docker.com/registry/spec/api/#listing-repositories

**Comment by parabuzzle** [comment]
@leominov,

in today's release of version 2.2 I've changed the catalog fetch to be recursive (if you have enough containers to choke loading them all into a single json object, I'm not sure craneop is right for you) and I added a filter box to allow you to narrow the list down. 

Please check it out and let me know what you think. I can add pagination but I think with the filter box, it may be a moot point now.

`docker run parabuzzle/craneoperator:2.2.1`

*note: I changed some environment variables in version 2.2 ... view the README.md at the root of this repo to see the changes*

**Comment by parabuzzle** [comment]
closing this because pagination is no longer needed with filtering.
