### ISSUE TITLE
Add ability to delete an image

### ISSUE THREAD

**Issue by parabuzzle** [parabuzzle/craneoperator#7]
https://docs.docker.com/registry/spec/api/#deleting-an-image

Things that need to be done here: 

- [x] api endpoint added to handle this action
- [x] a confirmation modal that requires an input like 'DELETE' to confirm added
- [x] activation of delete by environment variable like `ALLOW_IMAGE_DELETE=true`

**Comment by brunnels** [comment]
I'm interested in this as well.  Maybe just don't worry about security and if security is needed just configure nginx proxy container?

**Comment by parabuzzle** [comment]
@brunnels I think I solved the security problem. You can secure with BASIC auth by passing in a username and password at run time via the environment:

```
docker run -d \
  -p 80:80 \
  -e REGISTRY_HOST=registry.yourdomain.com \
  -e REGISTRY_PORT=443 \
  -e REGISTRY_PROTO=https \
  -e REGISTRY_SSL_VERIFY=false \
  -e USERNAME=admin \
  -e PASSWORD=s3cr3t \
  parabuzzle/craneoperator:latest
```

And I also support registry basic auth via these variables:

```
REGISTRY_USERNAME
REGISTRY_PASSWORD
```

So really this ticket just needs a confirmation dialog and the endpoint handling added.. 

Ideally I would like it to work like deleting a github repository. So you click the trash can icon and it pops up with a "Are you sure? Please type the word 'DELETE' in the box to confirm". or something like that..

I also think an environment variable on the container to all non-readonly actions like:

```
ALLOW_IMAGE_DELETE=true
```

I'll update the ticket to reflect this. And I'll try to find time to implement it.. unless you want to try ;)

**Comment by brunnels** [comment]
I'm not very familiar with ruby but there is another ruby registry UI that you could maybe borrow some code from.  https://hub.docker.com/r/klausmeyer/docker-registry-browser/

I think your layout is nicer and your details page is more detailed.

**Comment by parabuzzle** [comment]
@brunnels I think I've got a pretty good idea on how to execute this feature now. I'll try to block some time this weekend to work on it :)

**Comment by brunnels** [comment]
Great, looking forward to it and I'll be happy to test once you get something ready.  Thanks for sharing your hard work.

**Comment by parabuzzle** [comment]
@brunnels I got it working and pushed version 2.1.0 up to dockerhub. 

A few things to note:

1) you need to activate it by setting the environment variable `REGISTRY_ALLOW_DELETE`:

```
docker run -d \
  -e REGISTRY_HOST=192.168.0.1 \
  -e REGISTRY_ALLOW_DELETE=true \
  parabuzzle/craneoperator:2.1.0
```

2) You need to activate deletes on your registry in the registry config.yml under the storage section:

```yaml
storage:
  filesystem: ...
  delete:
    enabled: true
```

3) I've noticed with inmemory cache enabled, the delete isn't reflected on the api (and therefore the UI) right away. I fixed it locally by removing the cache block from the config entirely because we don't hit our registry all that often.

```yaml
storage:
  filesystem: ...
  #cache:
  #    blobdescriptor: inmemory
```

Let me know if anything blows up on your end.. I already updated my local version :)

**Comment by brunnels** [comment]
I'll try it out today. Thank you for the quick response.

**Comment by brunnels** [comment]
Looks good.  I think I saw the same behavior with the cache block enabled.  I get a spinner after deleting the tag.

What I don't see if how do you remove a repo that contains no tags?

**Comment by parabuzzle** [comment]
@brunnels there isn't an api endpoint for deleting a repo via the http api that I could find. 

https://docs.docker.com/registry/spec/api/
